### ISSUE TITLE
How to specify angle of a link solid to another link 

### ISSUE THREAD

**Issue by jumpinbanco** [gabemorris12/mechanism#1]
In example of four bar linkage, link e is integral with link c and sits at a fixed angle with respect to it. I cannot find anything in the code to govern such behaviour. 

Is it possible in general to specify for link a link: 
1. which link to be integral with? 
2. at what angle with respect to such link to sit at?

**Comment by gabemorris12** [comment]
Just to be clear, you are referring to `fourbarlinkage.py` from the examples folder: 

```
from mechanism import *
import numpy as np
import matplotlib.pyplot as plt

# Joint.follow_all = True  # You can trace the path of all joints by uncommenting this

O, A, B, C, D = get_joints('O A B C D')
D.follow = True
B.follow = True

a = Vector((O, A), r=5)
# b = Vector((O, C), r=8, theta=np.deg2rad(90), style='ground')  # Use this vector for a cusp output
b = Vector((O, C), r=8, theta=0, style='ground')
c = Vector((A, B), r=8)
d = Vector((C, B), r=9)
e = Vector((A, D), r=4)
f = Vector((O, D), show=False)


def loops(x, inp):
    # Note: The way this is structured with the second loop equation is only appropriate for position analysis.
    temp = np.zeros((2, 2))
    temp[0] = a(inp) + c(x[0]) - d(x[1]) - b()
    temp[1] = a(inp) + e(x[0] + np.deg2rad(30)) - f(x[2], x[3])
    return temp.flatten()


t2 = np.linspace(0, 6*np.pi, 300)
guess = np.concatenate((np.deg2rad([50, 120]), np.array([5]), np.deg2rad([50])))
mechanism = Mechanism(vectors=(a, b, c, d, e, f), origin=O, pos=t2, guess=(guess, ),
                      loops=loops)

mechanism.iterate()
ani, fig, ax = mechanism.get_animation()

ax.set_title('Four Bar Linkage')

plt.show()

# ani.save('../animations/fourbarlinkage.mp4', dpi=300)
```
First off, in order to use this package, you will have to have a good understanding of machinery mechanics. Although I didn't include one with each example, it is always the best practice to draw a free body diagram showing the joint/vector/DOF labels (DOF = degrees of freedom). Here is the FBD of this mechanism, which matches the labels in the code:

![image](https://user-images.githubusercontent.com/73252281/191060633-b1dd9f95-e6d7-466f-aa92-a78827a6b1f4.png)

![image](https://user-images.githubusercontent.com/73252281/191060885-f4a8145a-2471-426d-b4ea-c14b6c4f29c8.png)

There are four links in this mechanism. Link c and e are fixed together as one, but we are interested in understanding the kinematics of any point resting on that link (point D), which is why I have defined it as such. If you calculate the mobility like I did in the read me, you will find that it comes out to be 1, meaning we will need only 1 input to define the kinematics of this mechanism. This is vector A's angle. 

Again, there's a lot to understand, so I will just go ahead and answer your specific questions. 

> Is it possible to specify which links to be integral with one another? 

Links are connected at joints, which is always the first thing that is defined in all the examples. After defining the joints, you can define the vectors in which the first argument is a tuple of the tail and head joint. For instance, vector a was defined from O to A, so we have the line written as `a = Vector((O, A), r=5)`. Therefore, *you define the links to be connected at the declaration of the vector object when specifying the joints*.

Now the second question that relates to this one: 

> How is vector e shown to be at a fixed angle with respect to c?

How the mechanism gets solved is determined by 2 things: 

* Was the angle of the vector, length of the vector, both, or neither length or angle defined when declaring the vector object? This will determine the total degree of freedoms and the expected number of arguments for each vector in the loop equations. If both are defined (the case for vector b), then the link will show as fixed in the animation, and the `__call__` method for the vectors in the loop equation will not need any arguments. If only the angle or only the length is defined, then the call method will expect only one argument (the rest of the vectors except for f). If no arguments are given at the vector declaration, then the call method will expect two arguments (the case for vector f). For the no arguments case, the call method signature is Vector(length, angle). 
* Secondly, the loop equation is what ultimately determines how the mechanism gets solved. For this example, 
```
def loops(x, inp):
    # Note: The way this is structured with the second loop equation is only appropriate for position analysis.
    temp = np.zeros((2, 2))
    temp[0] = a(inp) + c(x[0]) - d(x[1]) - b()
    temp[1] = a(inp) + e(x[0] + np.deg2rad(30)) - f(x[2], x[3])
    return temp.flatten()
```
The reason why vector e is always 30 degrees with respect to c is because I passed the `x[0] + np.deg2rad(30)` as the angle argument for the `__call__` method. By defining this, the solver is always solving for the angle of vector e to be 30 degrees more than the angle for vector c. I did also note that this is not accurate if this analysis were extended to velocity or acceleration. Constructing the loop equation is the most difficult part of all of these problems. It is best to practice what I showed you with labelling the degrees of freedom and matching them up with the code.

There is a lot to show about this package, but it hasn't gotten enough attention for me to put forth video tutorials explaining it, but I would be willing to set up a teams meeting to explain this further. If you shoot me an email, we can set something up.
