### ISSUE TITLE
Specifying initial positions of joints in linkage mechanism?

### ISSUE THREAD

**Issue by palapav** [gabemorris12/mechanism#4]
Hi,
I was wondering if it is currently possible to specify the joints' initial positions (preferably as cartesian coordinates) in a linkage prior to iterating/generating a path of motion?

For example, in the below code snippet:

```
from mechanism import *
import numpy as np
import matplotlib.pyplot as plt

# Declare the joints that make up the system.
O, A, B, C = get_joints('O A B C')

# Declare the vectors and keep in mind that angles are in radians and start from the positive x-axis.
a = Vector((O, A), r=5)
b = Vector((A, B), r=8)
c = Vector((O, C), r=8, theta=0, style='ground')
d = Vector((C, B), r=9)
```

Is it possible to specify initial joint positions that would then get used by the mechanism object?

Also, thank you for your great contribution! It's really modular and readable 👍

**Comment by gabemorris12** [comment]
Aditya,

Thank you for your kind words!

There is a way to create a mechanism based off of initial conditions, but the process is not built into `mechanism`. What you can do is create your coordinates, then define the vectors in terms of the coordinates. You also need to make sure that your position input agrees with your initial coordinate points. Here is an example with the four bar linkage that you brought up:

```
from mechanism import *
import numpy as np
import matplotlib.pyplot as plt

# Initial points
# It's less work if we use the complex vector form (x, y) ---> x + i*y
O_point = 0 + 1j*0  # (0, 0)
A_point = 2 + 1j*3  # (2, 3)
B_point = 9 + 1j*7  # (9, 7)
C_point = 10 + 1j*0  # (10, 0)

# Make the vectors with respect to each other
R_AO = A_point - O_point  # Position vector of A with respect to O
R_BA = B_point - A_point  # Position vector of B with respect to A
R_CO = C_point - O_point  # Position vector of C with respect to O
R_BC = B_point - C_point  # Position vector of B with respect to C

# Declare the joints that make up the system
O, A, B, C = get_joints('O A B C')

# Declare the vectors and keep in mind that angles are in radians and start from the positive x-axis
a = Vector((O, A), r=np.abs(R_AO))
b = Vector((A, B), r=np.abs(R_BA))
c = Vector((O, C), r=np.abs(R_CO), theta=np.angle(R_CO), style='ground')
d = Vector((C, B), r=np.abs(R_BC))

# Define the known input to the system.
# For a 500 RMP crank, the time it takes to rotate one rev is 0.12s
time = np.linspace(0, 0.12, 300)
angular_velocity = 50*np.pi/3  # This is 500 RPM in rad/s

theta = angular_velocity*time + np.angle(R_AO)  # Integrate to find the theta
omega = np.full((time.size,), angular_velocity)  # Just an array of the same angular velocity
alpha = np.zeros(time.size)

# Guess the unknowns
pos_guess = np.deg2rad([45, 90])
vel_guess = np.array([1000, 1000])
acc_guess = np.array([1000, 1000])


# Define the loop equation(s)
def loop(x, i):
    return a(i) + b(x[0]) - c() - d(x[1])


# Create the mechanism object
mechanism = Mechanism(vectors=(a, b, c, d), origin=O, loops=loop, pos=theta, vel=omega, acc=alpha,
                      guess=(pos_guess, vel_guess, acc_guess))

# Call mechanism.iterate() then get and show the animation
mechanism.iterate()
ani, fig_, ax_ = mechanism.get_animation(stamp=time, show_joints=True, velocity=True, acceleration=True)

plt.show()
```

This will produce an animation with the starting point being at the initial coordinate points defined. Here is the mechanism at time zero:

![Figure_1](https://github.com/gabemorris12/mechanism/assets/73252281/22861c3e-c778-43fd-b51f-7f37ce04c64e)

You can pause and go frame by frame with the mouse buttons (scroll wheel will pause), but this only works with an actual mouse. I think I may make it to where the default behavior is that this won't happen because I can imagine that it can be annoying for laptops.

Does this answer your question?

**Comment by palapav** [comment]
Yes, this helps a lot! Thanks, Gabe. I'll let you know if I have any more questions down the road.
